[project]
name = "mcpcrashcourse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp-use>=1.3.0",
    "mcp[cli]>=1.9.2",
]

[tool.uv.workspace]
members = [
    "venv",
]
